version: '3.6'

services:
  db:
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_PASSWORD: randompassword
      POSTGRES_USER: johndoe
      POSTGRES_DB: mydb
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
